import streamlit as st
st.title("My First App In Streamlit")
st.header("This is a header")
st.caption("This is a caption")
st.markdown("This is a markdown[ [link](https://www.google.com) ]")
City = st.radio("Radio", ("Egypt", "USA", "UK"))
st.markdown(f"Selected City: {City}")
st.selectbox("Select", ("Egypt", "USA", "UK"))
st.multiselect("Multiselect", ("Egypt", "USA", "UK"))
st.number_input("Number")
st.slider("Slider")
st.date_input("Date")
st.time_input("Time")
st.sidebar.write("Sidebar Header")
st.sidebar.title("Sidebar Title")
st.sidebar.caption("Sidebar Caption")
st.text_area("Text Area")
st.text_input("Text Input")